# Based on https://github.com/xray/master/.travis.yml
language: python
python:
  - "2.7"
notifications:
  email: false

addons:
  apt:
    packages:
    - libnetcdf-dev

# Setup anaconda
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-2.2.2-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  # Update conda itself
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

matrix:
  exclude:
    - python: "2.7"
      env: UPDATE_PYENV=''

# Install packages
install:
  - conda config --add channels https://conda.binstar.org/jjhelmus
  - conda env create --file slocum_environment.yml
  - source activate slocum
  - pip install -e ./
  - pip install coveralls

# Run test
script:
  - pytest --cov=slocum --cov-report term-missing ./test/

after_success:
  - coveralls
