name: slocum
channels:
    - conda-forge
dependencies:
- python=3.7
- pip
- numpy
- scipy
- xarray >= 0.18.0
- pyproj >= 1.9.3
- pandas >= 0.13.1
- matplotlib >= 1.2.0
- joblib
- cartopy
- requests
- pytest
- netCDF4
- dask
- geopandas
- cfgrib
- pip:
    - pytest-xdist
    - pytest-coverage
