name: slocum
dependencies:
- python=2.7
- numpy
- scipy
- xray >= 0.3.1
- pyproj >= 1.9.3
- pandas >= 0.13.1
- matplotlib >= 1.2.0
- joblib
- basemap
- requests
- pytest
- netCDF4
- pip:
    - pytest-xdist
    - pytest-coverage
