ENSEMBLE = 'ens'
ENS_SPREAD_WS = 'ws_spread'
TIME = 'time'
HOURS = 'hours'
LAT = 'latitude'
LON = 'longitude'
UWND = 'uwnd'
VWND = 'vwnd'
PRECIP = 'precip'
CLOUD = 'cloud_cover'
PRESSURE = 'pressure'
UNITS = 'units'
BEARING = 'bearing'
HEADING = 'heading'
SPEED = 'speed'
DISTANCE = 'distance'
RELATIVE_WIND = 'rel_wind'
MOTOR_ON = 'motor_on'
WIND = 'wind'
WIND_SPEED = 'wind_speed'
WIND_DIR = 'wind_dir'
STEP = 'step'
NUM_STEPS = 'num_steps'

to_grib1 = {UWND: "u-component of wind",
            VWND: "v-component of wind"}
